[platformio]
src_dir = .

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 38400
lib_deps =
  fortyseveneffects/MIDI Library @ ^5.0.2
  https://github.com/bremme/arduino-tm1637.git
  paulstoffregen/Encoder @ ^1.4.4
  waspinator/CD74HC4067 @ ^1.0.2
  martinsos/HCSR04 @ ^2.0.0
