[platformio]
src_dir = .

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 38400
build_flags =
  -DAPP_BOARD_PROFILE=BOARD_NANO
  -DAPP_WIRING_PROFILE_HEADER='"wirings/nano_default.h"'
  -DAPP_MAPPING_PROFILE=MAPPING_DEFAULT
  -DAPP_MIDI_TRANSPORT=MIDI_TRANSPORT_SERIAL
lib_deps =
  fortyseveneffects/MIDI Library @ ^5.0.2
  https://github.com/bremme/arduino-tm1637.git
  paulstoffregen/Encoder @ ^1.4.4
  waspinator/CD74HC4067 @ ^1.0.2
  martinsos/HCSR04 @ ^2.0.0

[env:promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 38400
build_flags =
  -DAPP_BOARD_PROFILE=BOARD_PRO_MICRO
  -DAPP_WIRING_PROFILE_HEADER='"wirings/pro_micro_default.h"'
  -DAPP_MAPPING_PROFILE=MAPPING_DEFAULT
  -DAPP_MIDI_TRANSPORT=MIDI_TRANSPORT_USB
lib_deps =
  fortyseveneffects/MIDI Library @ ^5.0.2
  arduino-libraries/MIDIUSB @ ^1.0.5
  https://github.com/bremme/arduino-tm1637.git
  paulstoffregen/Encoder @ ^1.4.4
  waspinator/CD74HC4067 @ ^1.0.2
  martinsos/HCSR04 @ ^2.0.0
